spring.application.name=ChatBotProject

server.port = 8086

spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.project-id = ${GOOGLE_GENAI_PROJECT_ID}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash
spring.ai.google.genai.chat.options.temperature=0.7

spring.ai.google.genai.embedding.api-key=${GOOGLE_GENAI_API_KEY}

logging.level.org.springframework.ai.chat.client.advisor=DEBUG